name: Build and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the workflow repository
      uses: actions/checkout@v2

    - name: Clone target repository
      run: |
        git clone https://github.com/equalitie/ouisync.git
        cd ouisync
        if [ "$(git rev-parse HEAD)" == "$(cat ../last_commit)" ]; then
          echo "No new commits, exiting..."
          exit 0
        else
          git rev-parse HEAD > ../last_commit
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd ouisync/docker
        docker build -t ghcr.io/${{ github.repository_owner }}/ouisync:latest .
        docker push ghcr.io/${{ github.repository_owner }}/ouisync:latest

    - name: Clean up
      run: |
        rm -rf ouisync
