name: Build and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the workflow repository
      uses: actions/checkout@v2

    - name: Clone target repository
      run: |
        git clone https://github.com/equalitie/ouisync.git
        cd ouisync
        if [ "$(git rev-parse HEAD)" == "$(cat ../last_commit)" ]; then
          echo "No new commits, exiting..."
          exit 0
        else
          echo "Current hash: $(git rev-parse HEAD)"
          echo "Previous hash: $(cat ../last_commit)"
          git rev-parse HEAD > ../last_commit
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd ouisync
        LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$LOWERCASE_REPO_OWNER/ouisync:latest . -f docker/Dockerfile
        docker push ghcr.io/$LOWERCASE_REPO_OWNER/ouisync:latest

    - name: Clean up
      run: |
        rm -rf ouisync
