name: Build and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout the workflow repository
      uses: actions/checkout@v2

    - name: Clone target repository
      run: |
        git clone https://github.com/equalitie/ouisync.git
        cd ouisync
        if [ ! -f ../last_commit ]; then
          echo "Creating last_commit file..."
          git rev-parse HEAD > ../last_commit
          exit 0
        elif [ "$(git rev-parse HEAD)" == "$(cat ../last_commit)" ]; then
          echo "No new commits, exiting..."
          exit 0
        else
          echo "Current hash: $(git rev-parse HEAD)"
          echo "Previous hash: $(cat ../last_commit)"
          latest_commit=$(git rev-parse HEAD)
          echo "LATEST_COMMIT=${latest_commit}" >> $GITHUB_ENV
        fi
        
    - name: Save the commit hash to a file
      run: |
        echo "$LATEST_COMMIT" > last_commit

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add last_commit
        git commit -m "Save latest commit hash"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd ouisync
        LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        # Build Docker image
        docker build -t ghcr.io/$LOWERCASE_REPO_OWNER/ouisync:latest . -f docker/Dockerfile

        docker push ghcr.io/$LOWERCASE_REPO_OWNER/ouisync:latest

    - name: Clean up
      run: |
        rm -rf ouisync
