name: Build and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the workflow repository
      uses: actions/checkout@v2

    - name: Clone target repository
      run: |
        git clone https://github.com/equalitie/ouisync.git
        cd ouisync
        if [ ! -f ../last_commit ]; then
          echo "Creating last_commit file..."
          git rev-parse HEAD > ../last_commit
          exit 0
        elif [ "$(git rev-parse HEAD)" == "$(cat ../last_commit)" ]; then
          echo "No new commits, exiting..."
          exit 0
        else
          echo "Current hash: $(git rev-parse HEAD)"
          echo "Previous hash: $(cat ../last_commit)"
          git rev-parse HEAD > ../last_commit
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: /usr/local/cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo index
      uses: actions/cache@v2
      with:
        path: /usr/local/cargo/git/index
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libfuse3-dev

    - name: Generate Cargo.lock file
      run: |
        cd ouisync
        cargo build --package ouisync-cli --release --bins

    - name: Commit Cargo.lock
      run: |
        cd ouisync
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add Cargo.lock
        git commit -m "chore: Update Cargo.lock" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Build and push Docker image
      run: |
        cd ouisync
        LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        # Build Docker image
        docker build -t ghcr.io/$LOWERCASE_REPO_OWNER/ouisync:latest . -f docker/Dockerfile

        docker push ghcr.io/$LOWERCASE_REPO_OWNER/ouisync:latest

    - name: Clean up
      run: |
        rm -rf ouisync
